### ISSUE TITLE
auto-run and background running

### ISSUE THREAD

**Issue by odkrys** [infinyte7/AndroidWebServer#1]
A simple android webserver that supports cors headers seems like this app is probably the only one.

Can you add autorun and background running function?
I wish I didn't have to manually launch this app every time the browser launches.

**Comment by odkrys** [comment]
https://play.google.com/store/apps/details?id=slowscript.httpfileserver&hl=ko&gl=US

**Comment by krmanik** [comment]
Hi, I missed the comment. It can be implemented but I may look into this later.

**Comment by odkrys** [comment]
Hi.
I emailed the developer of the app I linked above and he added the features.
custom header and auto-start.
I had to purchase the pro version for background running, but I got all the features I wanted anyway.

**Comment by krmanik** [comment]
Thats good.
